name: Test and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
   contents: write  # Ensure GitHub Actions can push to gh-pages

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
            persist-credentials: false  # Important for token-based authentication

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 22
            cache: 'npm'

        - name: Install Dependencies
          run: npm install

        - name: Build Project
          run: npm run build

        - name: Deploy to GitHub Pages
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: npm run deploy